### ISSUE TITLE
createsuperuser problem

### ISSUE THREAD

**Issue by prabhatpankaj** [andela-cnnadi/6ix-tests#2]
Hi I am using 
Django==1.11.2
djangorestframework==3.6.4
djangorestframework-jwt==1.11.0
drfdocs==0.0.11
PyJWT==1.5.3
pytz==2017.2
six==1.11.0
with python 2.7

for creating superuser 
python manage.py createsuperuser , I am getting this error .

in create_superuser
    account = self.create_user(email, password, kwargs)
TypeError: create_user() takes at most 3 arguments (4 given)

**Comment by afropolymath** [comment]
This has already been resolved. See issue #1.

**Comment by prabhatpankaj** [comment]
I solve this problem by creating another function _create-user 
Like this 
https://github.com/prabhatpankaj/NativeStarter/blob/master/Quiz/server/src/authentication/models.py
